"""Deterministic edge-bundle exporter for host-side C++ ordinal parity (pipeline test only).

This stage turns the validated exported model plus the matrix ``validation``
rows into three portable artifacts a C++17 harness can compile against:

- ``ordinal_model_params.hpp`` — the model as ``ostosense::generated::kOrdinalModel``
  (exact float32 hexadecimal literals),
- ``golden_vectors.hpp`` — the validation feature rows with the Python-reference
  probabilities and expected predicted class index (float32 hex literals),
- ``edge_export_manifest.json`` — provenance/hashes/scope, no metrics.

It reuses the canonical constants, the trainer's matrix validation, the
evaluator's complete training-manifest validation, and the canonical
``inference.predict_exported_model`` forward — nothing is redefined. Expected
probabilities/labels are generated **only** through inference (never from
ground-truth labels).

The generated model/vector headers are ENGINEERING_TEST_ONLY, SYNTHETIC_PIPELINE_
TEST_ONLY outputs and must not be committed into the production firmware include
path. A passing downstream parity run proves synthetic cross-language inference
mechanics only — not ESP32 deployment, firmware parity on hardware, or OSTOSENSE
performance.

CLI::

    PYTHONPATH=ai/src ai/.venv/bin/python -m ostosense_ai.edge_export \\
        --model /tmp/ostosense-model \\
        --matrix /tmp/ostosense-matrix \\
        --output /tmp/ostosense-edge
"""

from __future__ import annotations

import argparse
import math
import struct
import tempfile
from pathlib import Path
from typing import Any

from ostosense_ai import inference, matrix, model_evaluation, training

EXPORTER_VERSION = "0.1.1"
ALLOWED_ORIGIN = matrix.ALLOWED_ORIGIN
FEATURE_COLUMNS = matrix.FEATURE_COLUMNS
CLASS_NAMES = matrix.CLASS_NAMES
VALIDATION_PARTITION = "validation"
FINAL_TEST_PARTITION = "final_test"
PROBABILITY_TOLERANCE = 1e-5
FLOAT_REPRESENTATION = "float32_hexadecimal_literals"
_OUTPUT_FILES = ("ordinal_model_params.hpp", "golden_vectors.hpp", "edge_export_manifest.json")
_GENERATED_NAMESPACE = "ostosense::generated"
GENERATED_WARNING = (
    "AUTO-GENERATED by ostosense_ai.edge_export -- ENGINEERING_TEST_ONLY, "
    "SYNTHETIC_PIPELINE_TEST_ONLY. Test-only fixture: do NOT commit into the "
    "production firmware include path. Not ESP32 deployment, not firmware parity "
    "on hardware, not OSTOSENSE performance."
)
MANIFEST_WARNING = (
    "SYNTHETIC_PIPELINE_TEST_ONLY ENGINEERING_TEST_ONLY edge bundle for host-side "
    "C++ inference parity. It proves synthetic cross-language inference mechanics "
    "only, never OSTOSENSE accuracy, notification, early-warning, sensor, clinical, "
    "or firmware performance on hardware."
)


class EdgeExportError(ValueError):
    """Edge-bundle export failure (leaves outputs untouched)."""


# --------------------------------------------------------------------------- #
# float32 hexadecimal literals (exact, portable to C++)
# --------------------------------------------------------------------------- #
def _to_float32(value: float) -> float:
    """Return a Python float holding the exact nearest finite float32."""
    try:
        result = struct.unpack("<f", struct.pack("<f", float(value)))[0]
    except (OverflowError, TypeError, ValueError, struct.error) as error:
        raise EdgeExportError(f"value is not representable as float32: {value!r}") from error
    if not math.isfinite(result):
        raise EdgeExportError(f"value is not representable as finite float32: {value!r}")
    return result


def _f32_literal(value: float) -> str:
    """Exact C++ float hexadecimal-floating literal for the nearest float32."""
    return _to_float32(value).hex() + "f"


def _array_literal(values) -> str:
    return "{" + ", ".join(_f32_literal(v) for v in values) + "}"


# --------------------------------------------------------------------------- #
# Validation (reuses the canonical validators; surfaces EdgeExportError)
# --------------------------------------------------------------------------- #
def _validate_chain(model_dir: Path, matrix_dir: Path):
    csv_path = matrix_dir / "model_matrix.csv"
    matrix_manifest_path = matrix_dir / "matrix_manifest.json"
    model_path = model_dir / "ordinal_model.json"
    training_manifest_path = model_dir / "training_manifest.json"

    try:
        matrix_manifest = model_evaluation._load_json(matrix_manifest_path)
        rows = training._read_matrix_rows(csv_path)
        training._validate_matrix(
            matrix_manifest, rows, csv_path, {"accepted_dataset_origin": ALLOWED_ORIGIN}
        )

        if any(row["dataset_partition"] == FINAL_TEST_PARTITION for row in rows):
            raise EdgeExportError("final_test rows are present; refusing to export")
        if FINAL_TEST_PARTITION in matrix_manifest.get("partition_values", []):
            raise EdgeExportError("matrix declares a final_test partition; refusing to export")
        if matrix_manifest.get("source_partition_window_counts", {}).get(FINAL_TEST_PARTITION):
            raise EdgeExportError("matrix source partitions include final_test; refusing to export")

        model_artifact = model_evaluation._load_json(model_path)
        training_manifest = model_evaluation._load_json(training_manifest_path)
        model_sha = training._sha256_file(model_path)
        model_evaluation._validate_training_manifest(
            training_manifest,
            rows,
            model_sha=model_sha,
            matrix_csv_sha=training._sha256_file(csv_path),
            matrix_manifest_sha=training._sha256_file(matrix_manifest_path),
        )
        inference.validate_model_artifact(model_artifact)
    except (training.TrainingError, model_evaluation.ModelEvaluationError, inference.InferenceError) as error:
        raise EdgeExportError(str(error)) from error

    validation_rows = [r for r in rows if r["dataset_partition"] == VALIDATION_PARTITION]
    if not validation_rows:
        raise EdgeExportError("no eligible validation rows to export")

    return {
        "rows": validation_rows,
        "model_artifact": model_artifact,
        "model_sha": model_sha,
        "csv_path": csv_path,
        "matrix_manifest_path": matrix_manifest_path,
        "model_path": model_path,
        "training_manifest_path": training_manifest_path,
    }


def _quantize_scalar(name: str, value: float) -> float:
    try:
        return _to_float32(value)
    except EdgeExportError as error:
        raise EdgeExportError(f"{name} is not a usable float32 value") from error


def _quantize_vector(name: str, values) -> list[float]:
    return [
        _quantize_scalar(f"{name}[{index}]", value)
        for index, value in enumerate(values)
    ]


def _float32_sigmoid(name: str, value: float) -> float:
    if value >= 0.0:
        exp_value = _quantize_scalar(f"{name} exp", math.exp(-value))
        denominator = _quantize_scalar(f"{name} denominator", 1.0 + exp_value)
        return _quantize_scalar(name, 1.0 / denominator)
    exp_value = _quantize_scalar(f"{name} exp", math.exp(value))
    denominator = _quantize_scalar(f"{name} denominator", 1.0 + exp_value)
    return _quantize_scalar(name, exp_value / denominator)


def _predict_float32_preflight(params, feature_rows):
    """Mirror C++ float32 arithmetic to reject unusable generated bundles early."""
    probabilities = []
    predicted_indices = []
    for row_index, row in enumerate(feature_rows):
        eta = 0.0
        for feature_index in range(5):
            delta = _quantize_scalar(
                f"row {row_index} feature {feature_index} centered value",
                row[feature_index] - params["mean"][feature_index],
            )
            standardized = _quantize_scalar(
                f"row {row_index} feature {feature_index} standardized value",
                delta / params["scale"][feature_index],
            )
            term = _quantize_scalar(
                f"row {row_index} feature {feature_index} eta term",
                params["beta"][feature_index] * standardized,
            )
            eta = _quantize_scalar(f"row {row_index} eta", eta + term)

        cumulative = []
        for threshold_index in range(3):
            argument = _quantize_scalar(
                f"row {row_index} threshold {threshold_index} argument",
                params["theta"][threshold_index] - eta,
            )
            cumulative.append(
                _float32_sigmoid(
                    f"row {row_index} threshold {threshold_index} sigmoid", argument
                )
            )
        row_probabilities = [
            cumulative[0],
            _quantize_scalar(
                f"row {row_index} probability 1", cumulative[1] - cumulative[0]
            ),
            _quantize_scalar(
                f"row {row_index} probability 2", cumulative[2] - cumulative[1]
            ),
            _quantize_scalar(f"row {row_index} probability 3", 1.0 - cumulative[2]),
        ]
        total = 0.0
        for class_index, probability in enumerate(row_probabilities):
            if probability < -PROBABILITY_TOLERANCE or probability > 1.0 + PROBABILITY_TOLERANCE:
                raise EdgeExportError(
                    f"row {row_index} class {class_index} float32 probability is out of range"
                )
            total = _quantize_scalar(f"row {row_index} probability sum", total + probability)
        if abs(total - 1.0) > PROBABILITY_TOLERANCE:
            raise EdgeExportError(
                f"row {row_index} float32 probabilities do not sum to one"
            )
        best = 0
        for class_index in range(1, 4):
            if row_probabilities[class_index] > row_probabilities[best]:
                best = class_index
        probabilities.append(row_probabilities)
        predicted_indices.append(best)
    return {"probabilities": probabilities, "predicted_indices": predicted_indices}


def _prepare_float32_bundle(model_artifact, feature_rows, reference_prediction):
    """Validate the exact float32 model/features that generated C++ will consume."""
    params = inference.validate_model_artifact(model_artifact)
    quantized_params = {
        name: _quantize_vector(name, params[name])
        for name in ("mean", "scale", "beta", "theta")
    }
    if any(value <= 0.0 for value in quantized_params["scale"]):
        raise EdgeExportError("scaler.scale becomes non-positive after float32 quantization")
    theta = quantized_params["theta"]
    if not all(theta[index] < theta[index + 1] for index in range(len(theta) - 1)):
        raise EdgeExportError("theta is not strictly increasing after float32 quantization")

    quantized_model = {
        **model_artifact,
        "scaler": {
            **model_artifact["scaler"],
            "mean": quantized_params["mean"],
            "scale": quantized_params["scale"],
        },
        "beta": quantized_params["beta"],
        "theta": quantized_params["theta"],
    }
    quantized_rows = [
        _quantize_vector(f"validation feature row {row_index}", row)
        for row_index, row in enumerate(feature_rows)
    ]

    try:
        inference.validate_model_artifact(quantized_model)
    except inference.InferenceError as error:
        raise EdgeExportError(f"float32-quantized model is invalid: {error}") from error
    float32_prediction = _predict_float32_preflight(quantized_params, quantized_rows)

    max_probability_difference = 0.0
    for row_index, (reference_index, float32_index) in enumerate(
        zip(reference_prediction["predicted_indices"], float32_prediction["predicted_indices"])
    ):
        if reference_index != float32_index:
            raise EdgeExportError(
                "float32 quantization changes predicted class at validation row "
                f"{row_index}: {reference_index} -> {float32_index}"
            )
        for reference_probability, float32_probability in zip(
            reference_prediction["probabilities"][row_index],
            float32_prediction["probabilities"][row_index],
        ):
            emitted_reference = _to_float32(reference_probability)
            max_probability_difference = max(
                max_probability_difference,
                abs(reference_probability - float32_probability),
                abs(reference_probability - emitted_reference),
                abs(float32_probability - emitted_reference),
            )
    if max_probability_difference > PROBABILITY_TOLERANCE:
        raise EdgeExportError(
            "float32 quantization changes Python-reference probabilities beyond "
            f"{PROBABILITY_TOLERANCE}: max difference {max_probability_difference}"
        )

    return quantized_model, quantized_rows


# --------------------------------------------------------------------------- #
# Header generation
# --------------------------------------------------------------------------- #
def _model_params_header(model_artifact: dict[str, Any], model_sha: str) -> str:
    params = inference.validate_model_artifact(model_artifact)
    return (
        f"// {GENERATED_WARNING}\n"
        "#pragma once\n\n"
        '#include "ostosense/ordinal_inference.hpp"\n\n'
        f"namespace {_GENERATED_NAMESPACE} {{\n\n"
        "// ordinal_model.json SHA-256 identifier.\n"
        f'inline constexpr char kOrdinalModelSha256[] = "{model_sha}";\n\n'
        "inline constexpr OrdinalModel kOrdinalModel = {\n"
        f"    /* mean  */ {_array_literal(params['mean'])},\n"
        f"    /* scale */ {_array_literal(params['scale'])},\n"
        f"    /* beta  */ {_array_literal(params['beta'])},\n"
        f"    /* theta */ {_array_literal(params['theta'])},\n"
        "};\n\n"
        f"}}  // namespace {_GENERATED_NAMESPACE}\n"
    )


def _golden_vectors_header(feature_rows, prediction) -> str:
    lines = [
        f"// {GENERATED_WARNING}\n"
        "#pragma once\n\n"
        "#include <array>\n#include <cstddef>\n#include <cstdint>\n\n"
        '#include "ostosense/ordinal_inference.hpp"\n\n'
        f"namespace {_GENERATED_NAMESPACE} {{\n\n"
        "struct GoldenVector {\n"
        "  std::array<float, 5> features;\n"
        "  std::array<float, 4> reference_probabilities;\n"
        "  std::uint8_t expected_class_index;  // from Python inference, not ground truth\n"
        "};\n\n"
        f"inline constexpr std::size_t kGoldenVectorCount = {len(feature_rows)};\n\n"
        f"inline constexpr std::array<GoldenVector, {len(feature_rows)}> kGoldenVectors = {{{{\n"
    ]
    for features, probabilities, index in zip(
        feature_rows, prediction["probabilities"], prediction["predicted_indices"]
    ):
        lines.append(
            f"    GoldenVector{{ {_array_literal(features)}, "
            f"{_array_literal(probabilities)}, {int(index)} }},\n"
        )
    lines.append("}};\n\n")
    lines.append(f"}}  // namespace {_GENERATED_NAMESPACE}\n")
    return "".join(lines)


# --------------------------------------------------------------------------- #
# Output (staged, refuse-by-default)
# --------------------------------------------------------------------------- #
def _check_output_targets(output_dir: Path, *, overwrite: bool) -> None:
    if output_dir.exists() and not output_dir.is_dir():
        raise NotADirectoryError(f"output path is not a directory: {output_dir}")
    existing = [output_dir / name for name in _OUTPUT_FILES if (output_dir / name).exists()]
    if existing and not overwrite:
        names = ", ".join(path.name for path in existing)
        raise FileExistsError(
            f"output already contains edge artifacts: {names}; "
            "pass overwrite=True or --overwrite to replace them"
        )


def _write_output_artifacts(
    output_dir: Path, params_header: str, golden_header: str, manifest: dict[str, Any], *, overwrite: bool
) -> dict[str, Any]:
    """Stage all three artifacts; hash the two headers and record them in the manifest.

    The three ``replace`` calls are individually atomic but are not a single
    OS-level transaction across the files.
    """
    _check_output_targets(output_dir, overwrite=overwrite)
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".ostosense-edge-", dir=output_dir.parent) as tmp:
        stage = Path(tmp)
        (stage / "ordinal_model_params.hpp").write_text(params_header, encoding="utf-8")
        (stage / "golden_vectors.hpp").write_text(golden_header, encoding="utf-8")
        manifest = {
            **manifest,
            "output_sha256": {
                "ordinal_model_params_hpp": training._sha256_file(stage / "ordinal_model_params.hpp"),
                "golden_vectors_hpp": training._sha256_file(stage / "golden_vectors.hpp"),
            },
        }
        (stage / "edge_export_manifest.json").write_text(training._dump_json(manifest), encoding="utf-8")
        output_dir.mkdir(parents=True, exist_ok=True)
        for name in _OUTPUT_FILES:
            (stage / name).replace(output_dir / name)
    return manifest


# --------------------------------------------------------------------------- #
# Top-level
# --------------------------------------------------------------------------- #
def export_edge_bundle(
    model_dir: str | Path,
    matrix_dir: str | Path,
    output_dir: str | Path,
    *,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Export the C++ parity bundle from a validated model + matrix; return manifest."""
    model_dir = Path(model_dir)
    matrix_dir = Path(matrix_dir)
    chain = _validate_chain(model_dir, matrix_dir)
    validation_rows = chain["rows"]
    model_artifact = chain["model_artifact"]

    feature_rows = [[float(r[column]) for column in FEATURE_COLUMNS] for r in validation_rows]
    try:
        prediction = inference.predict_exported_model(model_artifact, feature_rows)
    except inference.InferenceError as error:
        raise EdgeExportError(f"exported inference failed: {error}") from error

    quantized_model, quantized_rows = _prepare_float32_bundle(
        model_artifact, feature_rows, prediction
    )
    params_header = _model_params_header(quantized_model, chain["model_sha"])
    golden_header = _golden_vectors_header(quantized_rows, prediction)

    manifest = {
        "exporter_version": EXPORTER_VERSION,
        "dataset_origin": ALLOWED_ORIGIN,
        "input_sha256": {
            "ordinal_model_json": chain["model_sha"],
            "training_manifest_json": training._sha256_file(chain["training_manifest_path"]),
            "model_matrix_csv": training._sha256_file(chain["csv_path"]),
            "matrix_manifest_json": training._sha256_file(chain["matrix_manifest_path"]),
        },
        "feature_order": list(FEATURE_COLUMNS),
        "class_order": list(CLASS_NAMES),
        "vector_count": len(validation_rows),
        "float_representation": FLOAT_REPRESENTATION,
        "probability_tolerance": PROBABILITY_TOLERANCE,
        "warning": MANIFEST_WARNING,
    }

    return _write_output_artifacts(
        Path(output_dir), params_header, golden_header, manifest, overwrite=overwrite
    )


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m ostosense_ai.edge_export",
        description="Deterministic ENGINEERING_TEST_ONLY edge-bundle exporter for C++ parity (pipeline test only).",
    )
    parser.add_argument("--model", required=True, help="Trained model artifact directory.")
    parser.add_argument("--matrix", required=True, help="Matrix artifact directory.")
    parser.add_argument("--output", required=True, help="Output directory for the edge bundle.")
    parser.add_argument("--overwrite", action="store_true", help="Explicitly replace existing edge artifacts.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    manifest = export_edge_bundle(args.model, args.matrix, args.output, overwrite=args.overwrite)
    print(
        f"edge bundle: {manifest['vector_count']} golden vectors "
        f"(float32 hex, tolerance {manifest['probability_tolerance']}) to {args.output}"
    )
    print(MANIFEST_WARNING)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
